# Generated by Django 2.1.1 on 2018-09-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='code',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
