# Generated by Django 2.1.1 on 2018-09-22 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0002_auto_20180922_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcourse',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ed.Term'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ed.Department'),
        ),
    ]
