# Generated by Django 2.1.1 on 2018-09-23 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ed', '0003_auto_20180922_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desciption', models.TextField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='edcourse',
            name='maj1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edcourse',
            name='maj2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edcourse',
            name='min1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edcourse',
            name='min2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='edcourse',
            name='crn',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='edcourse',
            name='instructor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goalcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.Course'),
        ),
        migrations.AddField(
            model_name='goalcourse',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.EducationalGoal'),
        ),
        migrations.AddField(
            model_name='goalcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
