# Generated by Django 2.1.1 on 2019-03-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0004_auto_20180923_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.EDCourse'),
        ),
    ]
