# Generated by Django 2.1.1 on 2019-04-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0005_auto_20190325_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalgoal',
            old_name='desciption',
            new_name='description',
        ),
    ]
