# Generated by Django 2.1.1 on 2019-07-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0007_educationalgoal_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalgoal',
            name='courses',
            field=models.ManyToManyField(limit_choices_to={'student': 'self__student'}, to='ed.EDCourse'),
        ),
    ]
