# Generated by Django 2.1.1 on 2019-07-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0009_auto_20190718_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalgoal',
            name='courses',
            field=models.ManyToManyField(limit_choices_to={'self__student__username': 'student__username'}, to='ed.EDCourse'),
        ),
    ]
