# Generated by Django 2.1.1 on 2019-07-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0010_auto_20190718_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalgoal',
            name='courses',
            field=models.ManyToManyField(to='ed.EDCourse'),
        ),
    ]
