# Generated by Django 2.1.1 on 2019-07-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0013_auto_20190730_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalgoal',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
