# Generated by Django 2.1.1 on 2019-08-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0014_auto_20190730_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='goalcourse',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='goalcourse',
            name='student',
        ),
        migrations.DeleteModel(
            name='GoalCourse',
        ),
    ]
