# Generated by Django 2.1.1 on 2019-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0015_auto_20190806_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcourse',
            name='is_whittier',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='edcourse',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
