# Generated by Django 2.1.1 on 2020-03-27 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ed', '0016_auto_20190825_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('crn', models.PositiveIntegerField(null=True)),
                ('instructor', models.TextField(null=True)),
                ('maj1', models.BooleanField(default=False)),
                ('maj2', models.BooleanField(default=False)),
                ('min1', models.BooleanField(default=False)),
                ('min2', models.BooleanField(default=False)),
                ('is_whittier', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('replacement', models.TextField(null=True)),
                ('reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ed.Term')),
            ],
        ),
        migrations.AlterField(
            model_name='edcourse',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ed.Term'),
        ),
    ]
