# Generated by Django 2.1.1 on 2020-04-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0017_auto_20200326_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcourse',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
