# Generated by Django 2.1.1 on 2020-04-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0019_auto_20200401_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedcourse',
            name='replacement',
        ),
    ]
