"""
Django settings for poetfolio project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import getpass
username = getpass.getuser()
etcpath = '/home/' + username + '/etc'

SECRET_KEY = os.environ.get('POETFOLIO_SECRET_KEY') or (
             'YOU_SHOULD_GENERATE_YOUR_OWN_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
if os.environ.get('POETFOLIO_PRODUCTION'):
    DEBUG = False
else:
    DEBUG = True

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'ed.apps.EdConfig',
    'vita.apps.VitaConfig',
    'reports.apps.ReportsConfig',
    'siteconfig.apps.SiteconfigConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django.static.jquery',
    'phonenumber_field',
    'bootstrap4',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'poetfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["ed/templates",
                 "vita/templates",
                 "poetfolio/templates",
                 "reports/templates",
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'poetfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DB_NAME = os.environ.get('POETFOLIO_DB_NAME') or 'poetfolio_dev'
DB_USER = os.environ.get('POETFOLIO_DB_USER') or 'poetfolio'
DB_PASSWORD = os.environ.get('POETFOLIO_DB_PASSWORD') or 'devdevdev'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
        'TEST': {
            'NAME': 'test_poetfolio',
        },
        'OPTIONS': {'charset': 'utf8'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
import getpass
username = getpass.getuser()
STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('POETFOLIO_STATIC') or (
              '/home/' + username + '/static')

# media files
MEDIA_ROOT = os.environ.get('POETFOLIO_MEDIA') or (
             '/home/' + username + '/media')
MEDIA_URL = '/media/'

# login/logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('POETFOLIO_EMAIL_HOST') or ''
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('POETFOLIO_EMAIL_USER') or ''
EMAIL_HOST_PASSWORD = os.environ.get('POETFOLIO_EMAIL_PASSWORD') or ''
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'scholars@whittier.edu'
SECURITY_EMAIL_SENDER = DEFAULT_FROM_EMAIL
EMAIL_SUBJECT_PREFIX = '[Dashboard] '
SERVER_EMAIL = 'scholars@whittier.edu'
LOGIN_URL = '/login/'

# PhoneNumber
PHONENUMBER_DEFAULT_REGION = 'US'

# Forces django to use temporary files for uploads
FILE_UPLOAD_HANDLERS = [ 'django.core.files.uploadhandler.TemporaryFileUploadHandler' ]
