# Generated by Django 2.1.1 on 2019-07-23 18:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='domain',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='mail_box',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='street',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
