# Generated by Django 2.1.1 on 2019-08-06 17:38

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0003_student_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
