# Generated by Django 2.1.1 on 2019-08-08 22:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0015_auto_20190806_1607'),
        ('vita', '0005_auto_20190807_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='application_essay',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_term_student_set', to='ed.Term'),
        ),
        migrations.AddField(
            model_name='student',
            name='grad_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_term_student_set', to='ed.Term'),
        ),
    ]
