# Generated by Django 2.1.1 on 2019-08-08 23:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vita', '0006_auto_20190808_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('resubmit', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='application_essay',
        ),
    ]
