# Generated by Django 2.1.1 on 2019-08-09 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0007_auto_20190808_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_submitted',
            field=models.DateTimeField(null=True),
        ),
    ]
