# Generated by Django 2.1.1 on 2019-08-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0010_application_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
