# Generated by Django 2.1.1 on 2019-08-09 23:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0011_auto_20190809_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
