# Generated by Django 2.1.1 on 2019-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0012_application_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=60)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
