# Generated by Django 2.1.1 on 2019-10-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0014_menu_item_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='order',
            field=models.CharField(default='1', max_length=2),
            preserve_default=False,
        ),
    ]
