# Generated by Django 2.1.1 on 2019-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0017_home_page_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='subtitle',
            field=models.CharField(max_length=120),
        ),
    ]
