# Generated by Django 2.1.1 on 2020-04-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0019_auto_20200129_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor_email',
            field=models.EmailField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=16),
        ),
    ]
