# Generated by Django 2.1.1 on 2020-04-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0020_auto_20200426_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
