# Generated by Django 2.1.1 on 2020-04-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0021_auto_20200426_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='EDmeeting_complete',
            field=models.BooleanField(default=True),
        ),
    ]
