# Generated by Django 2.1.1 on 2020-04-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0022_student_edmeeting_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='EDmeeting_complete',
            field=models.BooleanField(default=False),
        ),
    ]
