# Generated by Django 2.1.1 on 2020-05-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0023_auto_20200426_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PRmeeting_complete',
            field=models.BooleanField(default=False),
        ),
    ]
