# Generated by Django 2.1.1 on 2020-05-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0025_auto_20200506_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
