# Generated by Django 2.2.13 on 2020-06-26 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0026_student_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published'),
        ),
    ]
