# Generated by Django 2.2.13 on 2020-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0027_auto_20200626_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
