# Generated by Django 2.2.13 on 2020-07-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0029_off_campus_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='off_campus_experience',
            old_name='student',
            new_name='user',
        ),
    ]
