# Generated by Django 2.2.13 on 2020-07-30 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vita', '0030_auto_20200730_0104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Off_Campus_Experience',
            new_name='OffCampusExperience',
        ),
    ]
