# Generated by Django 2.2.13 on 2020-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0031_auto_20200730_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcampusexperience',
            name='experince_type',
            field=models.CharField(choices=[('UD', 'Undecided'), ('INT', 'Internship'), ('CBL', 'Community-Based Learning'), ('STA', 'Study Abroad'), ('REU', 'Research Esperience for Undergraduates')], max_length=20),
        ),
    ]
