# Generated by Django 2.2.13 on 2020-07-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0033_auto_20200730_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offcampusexperience',
            old_name='notes_director',
            new_name='director_notes',
        ),
    ]
