# Generated by Django 2.2.13 on 2020-07-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0034_auto_20200730_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offcampusexperience',
            old_name='essay',
            new_name='reflection',
        ),
    ]
