# Generated by Django 2.2.13 on 2020-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0036_auto_20200731_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcampusexperience',
            name='aproved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offcampusexperience',
            name='completed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
