# Generated by Django 2.2.13 on 2020-07-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0039_auto_20200731_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcampusexperience',
            name='approved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='offcampusexperience',
            name='completed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='offcampusexperience',
            name='experince_type',
            field=models.CharField(choices=[('UD', 'Undecided'), ('INT', 'Internship'), ('CBL', 'Community-Based Learning'), ('STA', 'Study Abroad'), ('REU', 'Research Esperience for Undergraduates')], default='UD', max_length=3),
        ),
    ]
