# Generated by Django 2.2.13 on 2020-08-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0040_auto_20200731_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcampusexperience',
            name='experince_type',
            field=models.CharField(choices=[('UD', 'Undecided'), ('INT', 'Internship'), ('CBL', 'Community-Based Learning'), ('STA', 'Study Abroad'), ('REU', 'Research Esperience for Undergraduates'), ('OTR', 'Other')], default='UD', max_length=3),
        ),
    ]
