# Generated by Django 2.2.13 on 2020-08-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0042_auto_20200808_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcampusexperience',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vita.Student'),
        ),
    ]
