# Generated by Django 2.2.13 on 2020-10-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0043_auto_20200808_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shared_url',
            field=models.CharField(default='3b190e76b05d38615f5296b9a60abf990e921fe166417b49a00bbb06175f775c', max_length=64),
        ),
    ]
