# Generated by Django 2.2.13 on 2020-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0045_remove_student_shared_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shared_url',
            field=models.CharField(default='577a2d5d5550871768b6c01c920a321b239631df8d47c99d9826f58a0ac7826b', max_length=64),
        ),
    ]
