# Generated by Django 2.2.13 on 2020-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0047_remove_student_shared_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shared_url',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
