# Generated by Django 2.1.1 on 2020-02-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0016_auto_20190825_1507'),
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.Course')),
            ],
        ),
    ]
